# Use the official PostgreSQL image
FROM postgres:13

# Set the PostgreSQL database environment variables
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
ENV POSTGRES_DB mydb

# Expose the PostgreSQL default port
EXPOSE 5432